site_name: SAMBA
theme:
    name: material

    # headers for navigating tabs
    features:
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.action.edit
    
    palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - footnotes

repo_url: https://github.com/asemposki/SAMBA

repo_name: asemposki/SAMBA

copyright: Copyright &copy; 2021-2023 BAND Collaboration